baseurl = "http://blog.cerowrt.org/"
languageCode = "en-us"
title = "CeroWrt notebook: On fixing the internet since 2011"
canonifyurls = true
watchIgnoreFiles = ["\\.#(\\w+)\\.(\\w+)"]
ignoreFiles = ["&\\.#"]
[params]
author = "Dave TÃ¤ht"
watchIgnoreFiles = ["\\.#(\\w+)\\.(\\w+)"]
ignoreFiles = ["&\\.#"]

